repos:
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
  - id: mypy
    language_version: python3
    args: [--ignore-missing-imports, --disallow-incomplete-defs, --warn-unused-ignores,  --warn-redundant-casts,  --warn-unreachable]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: "v0.22.0"
  hooks:
    - id: markdownlint
      files: \.md$
      language_version: "13.14.0"
      args:
      - --fix